### ISSUE TITLE
Different port than 1883 (tried1884) didn't work

### ISSUE THREAD

**Issue by IngoK1** [50ButtonsEach/flic-hub-sdk-mqtt-js#1]
Hello I just wanted to use the implementation with a different port than 1883 and was not successful. Anything else to be set up than just change the port in options?

**Comment by IngoK1** [comment]
Hello all,

mmh too bad nobody seems to monitor this Issue list. For all others trying to use the given examples .. after having a closer look to the examples I was able to identify the problem. In the examples there are comments written within the created dictionary (options). For the example to work you need to delete all comments from within the options dictionary.

I hope this helps others using this code provided.

I suggest the comments should be written outside of the dictionary. The written format indicates they coud be used and be adjusted as needed which is not the case.

Ingo

**Comment by claudiapfeiffer** [comment]
Hi Ingo,
Sorry for not getting back to you earlier!
But I see that you figured out a way. :)
It is interesting to hear that, because I never had this issue, I can leave the comments in the options and it still works (e.g. with port 1884 or another client_id).
But in case there will be a new version coming out, I will definitely put the comments outside!
Have a great day and thanks again!
Best, Claudia
